### ISSUE TITLE
{{site.baseurl}} leaves extra slash in outputed HTML on localhost

### ISSUE THREAD

**Issue by andrewofficer** [maciakl/Sample-Jekyll-Site#4]
I've just started a Jekyll site and I'm seeing this extra slash on all links. I'm working on Jekyll's localhost:4000. 

For example the code looks like: 
`<a href="{{site.baseurl}}/contact">Contact</a>`

HTML output:
`<a href="//contact">Contact</a>`

Can I fix this without amending all the links? The posts themselves are also seem dead, outputting "meta/2012/03/15/guest-blogs/"

Thanks,
A

**Comment by haim-ari** [comment]
baseurl: does not seem to solve this
